name: update

on:
  workflow_dispatch:
  schedule:
    # 日本時間午前0時
    - cron: '0 15 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch name as environment variable
        run: echo "NEW_BRANCH_NAME=chore-update-data-$(date '+%s')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x

      - name: Recreate image list
        run: deno task gen:images

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: 🍱 画像リストを更新
          branch: ${{ env.NEW_BRANCH_NAME }}
          delete-branch: true
          title: "🍱 画像リストを更新"
          body: "このPRは自動生成されました 🤖"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
